// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @dev Standard ERC20 interface
 */
interface IERC20 {
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);
    function transfer(address recipient, uint256 amount) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
}

/**
 * @title CrossChainBridge
 * @dev Facilitates multi-token settlements across different blockchain networks 
 *      (e.g., locking USDC on Polygon to release USDT on Arbitrum) using a 
 *      mocked cross-chain messaging protocol (like CCIP or LayerZero).
 */
contract CrossChainBridge {
    
    // Address of the centralized or decentralized Oracle/Relayer that verifies cross-chain messages
    address public relayer;
    address public owner;

    // Supported tokens on THIS chain (e.g., USDC, USDT)
    mapping(address => bool) public supportedTokens;

    // Track locked funds (Token Address => Amount)
    mapping(address => uint256) public totalLocked;

    // Mapping to prevent replay attacks of cross-chain messages
    mapping(bytes32 => bool) public processedMessages;

    event TokensLocked(
        address indexed sender, 
        address indexed token, 
        uint256 amount, 
        uint256 destinationChainId, 
        address destinationRecipient
    );

    event TokensReleased(
        bytes32 indexed messageId,
        address indexed recipient,
        address indexed token,
        uint256 amount
    );

    event TokenSupportUpdated(address indexed token, bool isSupported);

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner can perform this action");
        _;
    }

    modifier onlyRelayer() {
        require(msg.sender == relayer, "Only the authorized relayer can execute this");
        _;
    }

    constructor(address _relayer) {
        owner = msg.sender;
        relayer = _relayer;
    }

    /**
     * @dev Updates the relayer address (e.g., upgrading to a new CCIP router)
     */
    function setRelayer(address _relayer) external onlyOwner {
        relayer = _relayer;
    }

    /**
     * @dev Add or remove support for a specific ERC20 token on this chain.
     */
    function setTokenSupport(address _token, bool _isSupported) external onlyOwner {
        supportedTokens[_token] = _isSupported;
        emit TokenSupportUpdated(_token, _isSupported);
    }

    /**
     * @dev STEP 1: A user (buyer) locks their preferred token on the Source Chain.
     * @param _token The ERC20 token address they are paying with.
     * @param _amount The amount they are locking.
     * @param _destinationChainId The ID of the chain where the seller wants to receive funds.
     * @param _destinationRecipient The address of the seller on the destination chain.
     */
    function lockFundsForTransfer(
        address _token,
        uint256 _amount,
        uint256 _destinationChainId,
        address _destinationRecipient
    ) external {
        require(supportedTokens[_token], "Token not supported for cross-chain transfer");
        require(_amount > 0, "Amount must be greater than zero");
        require(_destinationRecipient != address(0), "Invalid recipient address");

        // Transfer tokens from the user to this bridge contract
        // Note: The user must have called approve() on the ERC20 token prior to this
        bool success = IERC20(_token).transferFrom(msg.sender, address(this), _amount);
        require(success, "Token transfer failed");

        totalLocked[_token] += _amount;

        // Emit event to be picked up by the off-chain Relayer / Oracle network
        emit TokensLocked(msg.sender, _token, _amount, _destinationChainId, _destinationRecipient);
    }

    /**
     * @dev STEP 2: The Relayer (Oracle network) triggers this on the Destination Chain
     *      to release the equivalent funds to the seller in their preferred token.
     * @param _messageId A unique ID generated by the cross-chain protocol to prevent replays.
     * @param _recipient The seller's address receiving the funds.
     * @param _token The token address to release on this chain.
     * @param _amount The amount to release.
     */
    function releaseFunds(
        bytes32 _messageId,
        address _recipient,
        address _token,
        uint256 _amount
    ) external onlyRelayer {
        require(!processedMessages[_messageId], "Message already processed");
        require(supportedTokens[_token], "Target token not supported on this chain");
        require(IERC20(_token).balanceOf(address(this)) >= _amount, "Bridge has insufficient liquidity");

        processedMessages[_messageId] = true;
        totalLocked[_token] -= _amount;

        // Release the tokens to the seller
        bool success = IERC20(_token).transfer(_recipient, _amount);
        require(success, "Token release failed");

        emit TokensReleased(_messageId, _recipient, _token, _amount);
    }

    /**
     * @dev Emergency function for owner to withdraw liquidity if needed.
     */
    function emergencyWithdraw(address _token, uint256 _amount) external onlyOwner {
        bool success = IERC20(_token).transfer(owner, _amount);
        require(success, "Withdrawal failed");
    }
}
